name: ci

on:
  merge_group:
  push:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"

