name: ci

on:
  merge_group:
  push:
    branches-ignore:
      - gh-readonly-queue/**
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"

