name: ci

on:
  merge_group:
  pull_request:
    

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: exit 1

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: exit 1
